/*
Приведений опір теплопередачі склопакетів
Джерело: ДСТУ 9191:2022 Теплоізоляція будівель. Метод вибору теплоізоляційного матеріалу для утеплення будівель
URL: https://bulhakov.dev/bilux-calc/appendixes/appendix-b/
**/

const windows = [
  {
    variant: "4M₁-8-4M₁", // Тип склопакету
    numberOfCameras: 1, // Кількість камер склопакету
    air: 100, // Вміст повітря, %
    krypton: 0, // Вміст криптону, %
    argon: 0, // Вміст аргону, %
    thermalResistance: 0.28, // Опір теплопередачі склопакету
    solarEnergyTransmittanceCoefficient: 0.75, // Коефіцієнт пропускання сонячної енергії
  },
  {
    variant: "4M₁-10-4M₁",
    numberOfCameras: 1,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.29,
    solarEnergyTransmittanceCoefficient: 0.75,
  },
  {
    variant: "4M₁-12-4M₁",
    numberOfCameras: 1,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.3,
    solarEnergyTransmittanceCoefficient: 0.75,
  },
  {
    variant: "4M₁-16-4M₁",
    numberOfCameras: 1,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.32,
    solarEnergyTransmittanceCoefficient: 0.75,
  },
  {
    variant: "4M₁-8-4M₁",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.3,
    solarEnergyTransmittanceCoefficient: 0.75,
  },
  {
    variant: "4M₁-10-4M₁",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.31,
    solarEnergyTransmittanceCoefficient: 0.75,
  },
  {
    variant: "4M₁-12-4M₁",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.32,
    solarEnergyTransmittanceCoefficient: 0.75,
  },
  {
    variant: "4M₁-16-4M₁",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.34,
    solarEnergyTransmittanceCoefficient: 0.75,
  },
  {
    variant: "4M₁-16-4M₁",
    numberOfCameras: 1,
    air: 0,
    krypton: 100,
    argon: 0,
    thermalResistance: 0.38,
    solarEnergyTransmittanceCoefficient: 0.75,
  },
  {
    variant: "4M₁-8-4K",
    numberOfCameras: 1,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.47,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-10-4K",
    numberOfCameras: 1,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.49,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-12-4K",
    numberOfCameras: 1,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.51,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-16-4K",
    numberOfCameras: 1,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.53,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-8-4K",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.53,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-10-4K",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.55,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-12-4K",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.57,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-16-4K",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.59,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-16-4K",
    numberOfCameras: 1,
    air: 0,
    krypton: 100,
    argon: 0,
    thermalResistance: 0.62,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4K-16-4K",
    numberOfCameras: 1,
    air: 0,
    krypton: 100,
    argon: 0,
    thermalResistance: 0.67,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁–8-4i",
    numberOfCameras: 1,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.51,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-10-4i",
    numberOfCameras: 1,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.53,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-12-4i",
    numberOfCameras: 1,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.56,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-16-4i",
    numberOfCameras: 1,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.59,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-8-4i",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.57,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-10-4i",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.6,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-12-4i",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.63,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-16-4i",
    numberOfCameras: 1,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.66,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-16-4i",
    numberOfCameras: 1,
    air: 0,
    krypton: 100,
    argon: 0,
    thermalResistance: 0.75,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-16-4i",
    numberOfCameras: 1,
    air: 0,
    krypton: 75,
    argon: 25,
    thermalResistance: 0.72,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-16-4i",
    numberOfCameras: 1,
    air: 0,
    krypton: 50,
    argon: 50,
    thermalResistance: 0.7,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-16-4i",
    numberOfCameras: 1,
    air: 0,
    krypton: 25,
    argon: 75,
    thermalResistance: 0.67,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
  {
    variant: "4M₁-6-4M₁-6-4M₁",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.42,
    solarEnergyTransmittanceCoefficient: 0.7,
  },
  {
    variant: "4M₁-8-4M₁-8-4M₁",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.45,
    solarEnergyTransmittanceCoefficient: 0.7,
  },
  {
    variant: "4M₁-10-4M₁-10-4M₁",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.47,
    solarEnergyTransmittanceCoefficient: 0.7,
  },
  {
    variant: "4M₁-12-4M₁-12-4M₁",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.49,
    solarEnergyTransmittanceCoefficient: 0.7,
  },
  {
    variant: "4M₁-16-4M₁-16-4M₁",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.52,
    solarEnergyTransmittanceCoefficient: 0.7,
  },
  {
    variant: "4M₁-6-4M₁-6-4M₁",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.44,
    solarEnergyTransmittanceCoefficient: 0.7,
  },
  {
    variant: "4M₁-8-4M₁-8-4M₁",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.47,
    solarEnergyTransmittanceCoefficient: 0.7,
  },
  {
    variant: "4M₁-8-4M₁-8-4M₁",
    numberOfCameras: 2,
    air: 0,
    krypton: 100,
    argon: 0,
    thermalResistance: 0.51,
    solarEnergyTransmittanceCoefficient: 0.7,
  },
  {
    variant: "4M₁-10-4M₁-10-4M₁",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.49,
    solarEnergyTransmittanceCoefficient: 0.7,
  },
  {
    variant: "4M₁-12-4M₁-12-4M₁",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.52,
    solarEnergyTransmittanceCoefficient: 0.7,
  },
  {
    variant: "4M₁-16-4M₁-16-4M₁",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.55,
    solarEnergyTransmittanceCoefficient: 0.7,
  },
  {
    variant: "4M₁-6-4M₁-6-4K",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.53,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-8-4M₁-8-4K",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.55,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-10-4M₁-10-4K",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.59,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-12-4M₁-12-4K",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.61,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-16-4M₁-16-4K",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.65,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-6-4M₁-6-4K",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.6,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-8-4M₁-8-4K",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.62,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4Μ₁-10-4Μ₁-10-4K",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.65,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-12-4M₁-12-4K",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.68,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-16-4M₁-16-4K",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.72,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4Μ₁-10-4Μ₁-10-4K",
    numberOfCameras: 2,
    air: 0,
    krypton: 100,
    argon: 0,
    thermalResistance: 0.85,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-10-4M₁-10-4K",
    numberOfCameras: 2,
    air: 0,
    krypton: 75,
    argon: 25,
    thermalResistance: 0.82,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-10-4M₁-10-4K",
    numberOfCameras: 2,
    air: 0,
    krypton: 50,
    argon: 50,
    thermalResistance: 0.8,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-10-4M₁-10-4K",
    numberOfCameras: 2,
    air: 0,
    krypton: 25,
    argon: 75,
    thermalResistance: 0.78,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4K-10-4M₁-10-4K",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.73,
    solarEnergyTransmittanceCoefficient: 0.5,
  },
  {
    variant: "4M₁-10-4K-10-4K",
    numberOfCameras: 2,
    air: 0,
    krypton: 100,
    argon: 0,
    thermalResistance: 1.28,
    solarEnergyTransmittanceCoefficient: 0.5,
  },
  {
    variant: "4K-10-4M₁-10-4K",
    numberOfCameras: 2,
    air: 0,
    krypton: 100,
    argon: 0,
    thermalResistance: 1.32,
    solarEnergyTransmittanceCoefficient: 0.5,
  },
  {
    variant: "4M₁-8-4M₁-8-4i",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.61,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-10-4M₁-10-4i",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.64,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-12-4M₁-12-4i",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.68,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-16-4M₁-16-4i",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.72,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-6-4M₁-6-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.64,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-8-4M₁-8-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.67,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-10-4M₁-10-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.71,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-12-4M₁-12-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.75,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-16-4M₁-16-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 0,
    argon: 100,
    thermalResistance: 0.8,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-10-4M₁-10-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 100,
    argon: 0,
    thermalResistance: 0.94,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-10-4M₁-10-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 75,
    argon: 25,
    thermalResistance: 0.9,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-10-4M₁-10-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 50,
    argon: 50,
    thermalResistance: 0.85,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4M₁-10-4M₁-10-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 25,
    argon: 75,
    thermalResistance: 0.78,
    solarEnergyTransmittanceCoefficient: 0.58,
  },
  {
    variant: "4i-10-4M₁-10-4i",
    numberOfCameras: 2,
    air: 100,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.93,
    solarEnergyTransmittanceCoefficient: 0.5,
  },
  {
    variant: "4i-10-4M₁-10-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 100,
    argon: 0,
    thermalResistance: 1.35,
    solarEnergyTransmittanceCoefficient: 0.5,
  },
  {
    variant: "4i-10-4M₁-10-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 75,
    argon: 25,
    thermalResistance: 1.28,
    solarEnergyTransmittanceCoefficient: 0.5,
  },
  {
    variant: "4i-10-4M₁-10-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 50,
    argon: 50,
    thermalResistance: 1.18,
    solarEnergyTransmittanceCoefficient: 0.5,
  },
  {
    variant: "4i-10-4M₁-10-4i",
    numberOfCameras: 2,
    air: 0,
    krypton: 25,
    argon: 75,
    thermalResistance: 1.14,
    solarEnergyTransmittanceCoefficient: 0.5,
  },
  {
    variant: "Подвійне скління в деревʼяних спарених плетіннях",
    numberOfCameras: 1,
    air: 1,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.39,
    solarEnergyTransmittanceCoefficient: 0.75,
  },
  {
    variant: "Потрійне скління в деревʼяних роздільно-спарених плетіннях",
    numberOfCameras: 2,
    air: 1,
    krypton: 0,
    argon: 0,
    thermalResistance: 0.55,
    solarEnergyTransmittanceCoefficient: 0.67,
  },
];
export default windows;
